coverage:
  status:
    project:
      default:
        target: 75%
        threshold: null
        base: auto
  ignore:
    - "src/tests/"
    - "scripts/"
    - "diagrams/"
    - "src/main/java/uk/gov/ons/ctp/response/lib/"