openapi: 3.0.2
info:
    title: RAS/RM Action Service
    description: A service for dealing with Actions - operations that are required on a survey case, such as print file batching or arranging a field visit.
    version: "1.0"

servers:
    - url: https://localhost:8151
      description: The default path for Action in ras-rm-docker-dev
    - url: http://localhost:8080
      description: The default path for Action when port-forwarding to GCP

tags:
    - name: info
      description: Informational endpoints.
    - name: actions
      description: Endpoints for interacting with actions.

paths:
    /actions/{id}:
        get:
            summary: Returns the information on an action by ID.
            description: Returns the details of the action with the given ID.
            tags:
                - actions
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                    type: string
                    format: uuid
                    example: 56d87c78-4741-4dd8-ae8c-7384fd1e42f2
            responses:
                '200':
                    description: The action was successfully retrieved.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ActionDTO'
                '404':
                    description: No action found by that ID.
                '500':
                    description: The ID provided wasn't a valid UUID.
    /health:
        get:
            summary: Returns health information about the service.
            description: Returns whether the service is up or not. An in-built Spring endpoint.
            security: []
            tags:
                - info
            responses:
                '200':
                    description: A JSON indicating whether the service is up or not.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: UP
                '404':
                    description: The service is incorrectly configured.
    /info:
        get:
            summary: Returns basic information about the service.
            description: Returns service information. An in-built Spring endpoint.
            security: []
            tags:
                - info
            responses:
                '200':
                    description: A JSON of basic information about the service.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    name:
                                        type: string
                                        example: actionsvc
                                    version:
                                        type: string
                                        example: "10.42.0"
                                    origin:
                                        type: string
                                        example: "git@github.com:ONSdigital/rm-action-service.git"
                                    commit:
                                        type: string
                                        example: "06752afbf05f27c923ddf42d3cd2ec9eeafd3362"
                                    branch:
                                        type: string
                                        example: master
                                    built:
                                        type: string
                                        format: date-time
                                        example: "2020-06-15T08:38:34Z"
                '404':
                    description: The service is incorrectly configured.
components:
    schemas:
        ActionDTO:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                    example: 56d87c78-4741-4dd8-ae8c-7384fd1e42f2
                caseId:
                    type: string
                    format: uuid
                    example: 75ac47f9-0a5a-47f2-91ea-39fcff6725d1
                actionPlanId:
                    type: string
                    format: uuid
                    example: 810e9501-832b-4156-8d84-157aa026872b
                actionRuleId:
                    type: string
                    format: uuid
                    example: 1ce958b4-4c12-4f69-9573-9b10fc22ea76
                actionTypeName:
                    type: string
                    example: HouseholdCreateVisit
                createdBy:
                    type: string
                    example: SYSTEM
                manuallyCreated:
                    type: boolean
                    example: False
                priority:
                    type: number
                    format: integer
                    example: 3
                situation:
                    type: string
                    example: DERELI
                state:
                    type: string
                    example: CANCEL_PENDING
                createdDateTime:
                    type: string
                    format: date-time
                    example: "2020-06-15T08:38:34Z"
                updatedDateTime:
                    type: string
                    format: date-time
                    example: "2020-06-15T08:38:34Z"
    securitySchemes:
        basicAuth:
            type: http
            scheme: basic

security:
    - basicAuth: []