version: '2'
services:
 postgres:
  container_name: postgres-action-it
  image: eu.gcr.io/ons-rasrmbs-management/postgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
  ports:
    - "16432:5432"
 pubsub-emulator:
   container_name: pubsub-emulator-it
   image: eu.gcr.io/ons-rasrmbs-management/pubsub-emulator
   ports:
     - "18681:8681"
   environment:
     - PUBSUB_PROJECT1=test,test_topic:test_subscription
