spring:
  main:
    # Added as part of upgrade to 2.1 to quiet a an error where the 'restExceptionHandler' bean is defined twice.
    allow-bean-definition-overriding: true

  liquibase:
    user: postgres
    password: postgres
    liquibase-schema: action
    url: jdbc:postgresql://localhost:16432/postgres

  output:
    ansi:
      enabled: never
  application:
    name: ONS ActionService

  datasource:
    url: jdbc:postgresql://localhost:16432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    continue-on-error: true
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        default_schema: action

    # Used to suppress warning that appeared after upgrade to spring 2.0. It defaults to true and we weren't setting
    # it so nothing changed.  Spring boot shows warnings if you don't explicitly set it.
    open-in-view: true

  security:
    user:
      name: admin
      password: secret