env: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

gcp:
  project: ras-rm-sandbox
  notifyTopic: ras-rm-notify-test
  printFileTopic: print-file-jobs
  bucket:
    name: "ras-rm-print-file"
    prefix: ""

container:
  port: 8080
service:
  port: 8080

crons:
  emailProcessor:
    name: action-email-processor
    cron: "*/5 * * * *"
    target: "process/emails"
  letterProcessor:
    name: action-letter-processor
    cron: "0 */1 * * *"
    target: "process/letters"
  planJobExecutor:
    name: action-plan-executor
    cron: "*/15 * * * *"
    target: "actionplans/execute"

resources:
  application:
    requests:
      memory: "250Mi"
      cpu: "100m"
    limits:
      memory: "1500Mi"
      cpu: "1000m"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 200
  cpuPercentage: 500
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

managedRabbitMQ:
  enabled: false

dns:
  enabled: false
  wellKnownPort: 8080

