env: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

zipkin:
  enabled: false

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "256Mi"

managedRabbitMQ:
  enabled: false

report:
  cron: "0 * * * * *"

planExecutionDelayMillis: 1000

dns:
  enabled: false
  wellKnownPort: 8080