env: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

gcp:
  project: ras-rm-sandbox
  notifyTopic: ras-rm-notify-test
  printFileTopic: print-file
  caseNotificationSubscription: ras-rm-case-notification-subscription
  bucket:
    name: "ras-rm-print-file"
    prefix: ""

container:
  port: 8080
service:
  port: 8080

crons:
  distributionScheduler:
    name: action-distribution-scheduler
    cron: "* * * * *"
    target: "distribute"
  planJobExecutor:
    name: action-plan-executor
    cron: "* * * * *"
    target: "actionplans/execute"
  recordDeleter:
    name: action-export-old-record-deleter
    cron: "0 3 * * *"
    target: "delete-old-data"
  exportScheduler:
    name: action-export-scheduler
    cron: "*/30 * * * *"
    target: "export"
  retryEventScheduler:
    name: action-event-retry-scheduler
    cron: "0 * * * *"
    target: "retry-event"
  partialEventScheduler:
    name: action-event-partial-retry-scheduler
    cron: "0 */2 * * *"
    target: "process-partial-event"

resources:
  application:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "600Mi"
      cpu: "500m"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 200
  cpuPercentage: 500
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

report:
  cron: "0 * * * * *"

planExecutionDelayMillis: 1000

dns:
  enabled: false
  wellKnownPort: 8080

messaging:
  consumingThreads: 10