env: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

gcp:
  project: ras-rm-sandbox
  notifyTopic: ras-rm-notify-test
  printFileTopic: print-file-jobs
  bucket:
    name: "ras-rm-print-file"
    prefix: ""

container:
  port: 8080
service:
  port: 8080

crons:
  emailProcessor:
    name: action-email-processor
    cron: "*/5 * * * *"
    target: "process/emails"
  letterProcessor:
    name: action-letter-processor
    cron: "0 */1 * * *"
    target: "process/letters"
  planJobExecutor:
    name: action-plan-executor
    cron: "*/15 * * * *"
    target: "actionplans/execute"

resources:
  requests:
    memory: "256Mi"

managedRabbitMQ:
  enabled: false

dns:
  enabled: false
  wellKnownPort: 8080

