env: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

gcp:
  project: ras-rm-sandbox
  notifyTopic: ras-rm-notify-test
  printFileTopic: print-file-jobs
  bucket:
    name: "ras-rm-print-file"
    prefix: ""

container:
  port: 8080
service:
  port: 8080

crons:
  distributionScheduler:
    name: action-distribution-scheduler
    cron: "* * * * *"
    target: "distribute"
  planJobExecutor:
    name: action-plan-executor
    cron: "* * * * *"
    target: "actionplans/execute"
  recordDeleter:
    name: action-export-old-record-deleter
    cron: "0 3 * * *"
    target: "delete-old-data"
  exportScheduler:
    name: action-export-scheduler
    cron: "*/30 * * * *"
    target: "export"

resources:
  requests:
    memory: "256Mi"

managedRabbitMQ:
  enabled: false

report:
  cron: "0 * * * * *"

planExecutionDelayMillis: 1000

dns:
  enabled: false
  wellKnownPort: 8080

