@startuml
skinparam state {
    BackgroundColor HoneyDew
}

[*] --> SUBMITTED

SUBMITTED --> PENDING : request_distributed [[https://github.com/ONSdigital/rm-action-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/service/impl/ActionProcessingServiceImpl.java#L106 *]]
SUBMITTED --> COMPLETED : request_completed [[https://github.com/ONSdigital/rm-action-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/service/impl/ActionProcessingServiceImpl.java#L107 1]] [[https://github.com/ONSdigital/rm-actionexporter-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/export/message/impl/SftpServicePublisherImpl.java#L131 2]] [[https://github.com/ONSdigital/rm-actionexporter-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/export/message/impl/SftpServicePublisherImpl.java#L130 3]] [[https://github.com/ONSdigital/rm-notify-gateway/blob/master/src/main/java/uk/gov/ons/ctp/response/notify/service/impl/NotifyServiceImpl.java#L227 4]]
SUBMITTED --> ABORTED : request_cancelled [[https://github.com/ONSdigital/rm-action-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/service/impl/ActionServiceImpl.java#L109 *]]

PENDING --> SUBMITTED : request_failed
PENDING --> ACTIVE  : request_accepted  [[https://github.com/ONSdigital/rm-actionexporter-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/export/service/impl/ActionExportServiceImpl.java#L95 1]] [[https://github.com/ONSdigital/rm-notify-gateway/blob/master/src/main/java/uk/gov/ons/ctp/response/notify/message/impl/ActionInstructionReceiverImpl.java#L64 2]]
PENDING --> DECLINED : request_declined [[https://github.com/ONSdigital/rm-notify-gateway/blob/master/src/main/java/uk/gov/ons/ctp/response/notify/message/impl/ActionInstructionReceiverImpl.java#L76 *]]
PENDING --> COMPLETED : request_completed [[https://github.com/ONSdigital/rm-action-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/service/impl/ActionProcessingServiceImpl.java#L107 1]] [[https://github.com/ONSdigital/rm-actionexporter-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/export/message/impl/SftpServicePublisherImpl.java#L131 2]] [[https://github.com/ONSdigital/rm-actionexporter-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/export/message/impl/SftpServicePublisherImpl.java#L130 3]] [[https://github.com/ONSdigital/rm-notify-gateway/blob/master/src/main/java/uk/gov/ons/ctp/response/notify/service/impl/NotifyServiceImpl.java#L227 4]]
PENDING --> COMPLETED : request_completed_deactivate
PENDING --> COMPLETED : request_completed_disable

ACTIVE --> SUBMITTED : request_failed
ACTIVE --> COMPLETED : request_completed  [[https://github.com/ONSdigital/rm-action-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/service/impl/ActionProcessingServiceImpl.java#L107 1]] [[https://github.com/ONSdigital/rm-actionexporter-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/export/message/impl/SftpServicePublisherImpl.java#L131 2]] [[https://github.com/ONSdigital/rm-actionexporter-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/export/message/impl/SftpServicePublisherImpl.java#L130 3]] [[https://github.com/ONSdigital/rm-notify-gateway/blob/master/src/main/java/uk/gov/ons/ctp/response/notify/service/impl/NotifyServiceImpl.java#L227 4]]
ACTIVE --> COMPLETED : request_completed_deactivate
ACTIVE --> COMPLETED : request_completed_disable

COMPLETED --> COMPLETED : request_cancelled [[https://github.com/ONSdigital/rm-action-service/blob/master/src/main/java/uk/gov/ons/ctp/response/action/service/impl/ActionServiceImpl.java#L109 *]]

@enduml