apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.crons.action.plans.name }}
spec:
  schedule: "{{ .Values.crons.action.plans.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.crons.action.plan.name }}
              image: radial/busyboxplus:curl
              env:
                - name: SECURITY_USER_NAME
                  valueFrom:
                    secretKeyRef:
                      name: security-credentials
                      key: security-user
                - name: SECURITY_USER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: security-credentials
                      key: security-password
                - name: TARGET
                  value: {{ .Values.crons.action.plan.target }}
              args:
                - /bin/sh
                - -c
                - curl -u $(SECURITY_USER_NAME):$(SECURITY_USER_PASSWORD) http://$(ACTION_EXPORTER_SERVICE_HOST):$(ACTION_EXPORTER_SERVICE_PORT)/$(TARGET)
          restartPolicy: OnFailure